In [2]:
from mxnet import np, npx
npx.set_np()

In [3]:
x= np.arange(12)


In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [6]:
x.reshape(3,4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [7]:
x.reshape(2,-1)


array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [8]:
np.empty((3,4))

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 3.9572669e-42, 0.0000000e+00],
       [0.0000000e+00, 6.8663625e-44, 0.0000000e+00, 1.0561189e-38]])

In [9]:
np.empty((3, 4))

array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00],
       [0.000000e+00, 0.000000e+00, 3.990898e-42, 0.000000e+00],
       [0.000000e+00, 5.745324e-44, 0.000000e+00, 4.224511e-39]])

In [10]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.random.normal(0,1,size = (3,4))

array([[ 1.1630785 ,  2.2122061 ,  0.4838046 ,  0.7740038 ],
       [ 0.29956347,  1.0434403 ,  0.15302546,  1.1839255 ],
       [-1.1688148 ,  1.8917114 ,  1.558071  , -1.2347414 ]])

In [12]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [13]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [14]:
x = np.arange(12).reshape(3, 4)
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
x==y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [19]:
np.sum(x)

array(66.)

In [18]:
x.sum()

array(66.)

# 2.1.3: Cơ chế lan truyền


In [28]:
a = np.arange(3).reshape((3,1))
b=np.arange(2).reshape((1,2))

In [27]:
a+b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

# 2.1.4: Chỉ số và cắt nhọn bảng

In [29]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [32]:
x[-1], x[0:2,:]

(array([ 8.,  9., 10., 11.]),
 array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]))

In [35]:
x[2,2]=0
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9.,  0., 11.]])

In [36]:
x[0:2,:]=12
x

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9.,  0., 11.]])

# 2.1.5:Tiết kiệm bộ nhớ

In [37]:
before = id(y)
y = y + x
id(y) == before

False

In [38]:
y

array([[14., 13., 16., 15.],
       [13., 14., 15., 16.],
       [12., 12.,  2., 12.]])

In [41]:
z = np.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2339357140096
id(z): 2339357140096


In [42]:
before = id(x)
x += y
id(x) == before

True

# 2.1.6. Chuyển đổi sang các Đối Tượng Python Khác

In [43]:
a = x.asnumpy()
b = np.array(a)
type(a), type(b)

(numpy.ndarray, mxnet.numpy.ndarray)

In [44]:
#chuyển đổi một mảng ndarray sang số vô hướng
a = np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)