In [19]:
from mxnet import npx, np, autograd

In [21]:
npx.set_np()

In [8]:
x = np.arange(4)

In [42]:
x

array([0., 1., 2., 3.])

In [11]:
x.attach_grad() #create space to store gradian

In [12]:
x.grad

array([0., 0., 0., 0.])

In [36]:
with autograd.record():
    y = 2*np.dot(x,x)
y

array(28.)

In [37]:
y.backward()

In [38]:
x.grad

array([ 0.,  4.,  8., 12.])

In [41]:
with autograd.record():
    y = x * x  # y is a vector
y.backward()
print(y)

u = x.copy()
u.attach_grad()
with autograd.record():
    v = (u * u).sum()  # v is a scalar
v.backward()

x.grad == u.grad

[0. 1. 2. 3.]
[0. 1. 4. 9.]


array([ True,  True,  True,  True])

In [43]:
with autograd.record():
    y = x*x
    u = y.detach()
    z = u*x
    
z.backward()

In [47]:
x.grad == u


array([ True,  True,  True,  True])

In [46]:
x

array([0., 1., 2., 3.])

In [48]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True
